config/routes.rb
  Rails.application.routes.draw do  

       root "sessions#welcome"
     
       get 'login', to: 'sessions#new'   
       post 'login', to: 'sessions#create'  
       get 'welcome', to: 'sessions#welcome'   
       get 'authorized', to: 'sessions#page_requires_login'
       get '/logout' => 'sessions#destroy'
       get '/search', to: 'events#search'
       
       resources :users
       resources :events
       resources :rooms
       resources :password_resets

       get '/expried_index', to: 'events#expried_index'

  end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :room

    belongs_to :user

	  validates  :purpose, :start_date, :end_date, presence: true

    validates :people, :numericality => { :greater_than_or_equal_to => 1}

    validate :hour_check

    validate :room_check
    
    validate :dates_are_available, on: :create

    private
    def dates_are_available
     room = Room.find(self.room_id)
     conditions = []
     conditions << '(:new_start_date >= :new_end_date)'
     if user.role == "Empolyee"
     conditions << '(start_date >= :new_start_date AND end_date >= :new_end_date)'
     conditions << '(start_date >= :new_start_date AND end_date <= :new_end_date)'
     conditions << '(end_date BETWEEN :new_start_date AND :new_end_date)'
     conditions << '(start_date <= :new_start_date AND end_date >= :new_end_date)'
     end
      if room.events.where(conditions.join(' OR '), new_start_date: self.start_date, new_end_date: self.end_date).exists?
       self.errors.add(:base, 'Time already taken & Please enter valid time')
       return false
      end
    end
    

    def hour_check
     @hour = (start_date.to_i - end_date.to_i)/3600
     if @hour == -1
     else
      self.errors.add(:base, 'Hours not greater then 1')
     end
    end

    def room_check
      room = Room.find(self.room_id)
       if people.to_i > room.capacity.to_i
        self.errors.add(:base, 'This room is not for many people')
      end
    end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  
 before_action :set_event, only: %i[ show edit update destroy ]

  def index
    @events = Event.all
  end

  def show
  end

  def new
    @event = current_user.events.new
  end

  def edit
  end

  def create
    @event = current_user.events.create(event_params)
        if @event.save
          EventMailer.with(event: @event).event_send.deliver_now
          flash[:notice] = "Schedule created successfully."
          # @time = @event.start_date - 900
          # ConfirmMailer.with(event: @event).confirm_send.deliver_later(wait_until: @time)
          redirect_to @event
        else
          render :new, status: :unprocessable_entity
        end
  end

  def update
      if @event.update(event_params)
         UpdateMailer.with(event: @event).update_send.deliver_now
         flash[:notice] = "Schedule updated successfully."
         redirect_to @event
      else
         render :edit, status: :unprocessable_entity
      end
  end

  def destroy
    @event.destroy
     flash[:notice] = "Schedule Destroy successfully."  
     redirect_to root_path, status: :see_other
  end

  def search
      @event = params[:query]
      @events = Event.where("events.purpose like ?", ["%#{@event}%"])
      render :index
  end

  private
    def set_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:purpose, :people, :start_date, :end_date, :search, :room_id)
    end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event) do |form| %>
  <% if event.errors.any? %>
    <div style="color: red">
      <ul>
        <% event.errors.each do |error| %>
          <li style=" color: white;"><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :purpose, style: "display: block" %>
    <%= form.text_field :purpose %>
  </div>

  <div>
    <%= form.label :people, style: "display: block" %>
    <%= form.number_field :people %>
  </div>

  <div>
    <%= form.label :start_date, style: "display: block" %>
    <%= form.datetime_field :start_date %>
  </div>

  <div>
    <%= form.label :end_date, style: "display: block" %>
    <%= form.datetime_field :end_date %>
  </div><br>

  <p>Rooms: <%= form.select :room_id, Room.all.map { |room| [ room.room_name, room.id ] } %></p><br>

  <div>
    <%= form.submit %>
  </div>
  
<% end %>

app/views/events/edit.html.erb
<center>
<h1 style=" color: white;">Edit Schedule Meeting :-</h1>

<%= render "form", event: @event %><br>

<div>
<%= link_to "Back to users", root_path , class:"btn btn-success"%>
</div>
</center>

app/views/events/expried_index.html.erb
<center><h1 style=" color: white;">All Expried Meetings:-</h1></center>
<div class="row">
  <% Event.all.each do |event| %>
   <% if event.end_date < Time.now %>
   <div class="col-sm-4">
      <div class="card navbar-light bg-light"  style="background-image: url(https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQUHfjWn2Sa5jFNRnlbskEQdXyN1tRhH1dpdQ&usqp=CAU); background-repeat: no-repeat; background-size: cover;">
       <div class="card-body">
             <p><b> Purpose: </b><%= event.purpose %></p>
             <p><b> People: </b><%= event.people %></p>
             <p><b> Start Time: </b><%= event.start_date %></p>
             <p><b> End Time: </b><%= event.end_date %></p>
             <p><b> Room: </b><%= event.room.room %></p>
             <p style="color:red;">Meeting Expried</p>
             <p><b> Host: </b><%= event.user.to_s %></p>    
         <% if current_user.role == "HR" %>
         <%= button_to "Destroy this hosting", event, method: :delete , class:"btn btn-outline-danger"%>
         <% end %>  
       </div>
     </div> <br>
   </div> <% end %> 
    <% end %>
</div>
<br>
<%= link_to "Back to users", root_path , class:"btn btn-success"%>

app/views/events/index.html.erb
<center><h1 style=" color: white;">All Scheduled Meetings:-</h1></center>
<div class="row">
  <% @events.each do |event| %>
   <% if event.end_date > Time.now %>
   <div class="col-sm-4">
     <div class="card navbar-light bg-light"  style="background-image: url(https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQUHfjWn2Sa5jFNRnlbskEQdXyN1tRhH1dpdQ&usqp=CAU); background-repeat: no-repeat; background-size: cover;">
       <div class="card-body">
             <p><b> Purpose: </b><%= event.purpose %></p>
             <p><b> People: </b><%= event.people %></p>
             <p><b> Start Time: </b><%= event.start_date %></p>
             <p><b> End Time: </b><%= event.end_date %></p>
             <p><b> Room: </b><%= event.room.room %></p>
             <p><b> Host: </b><%= event.user.to_s %></p>

         <% if event.room.capacity.to_i-2 > event.people.to_i %>
         <% @res = event.room.capacity.to_i - event.people.to_i %>
          <span style="color: red;"><%= @res %> Seats are availble</span><br><br>
         <% end %>
         <% if current_user.role == "HR" %>
         <%= link_to "Edit this hosting", edit_event_path(event), class:"card-link" %> |
         <%= button_to "Destroy this hosting", event, method: :delete , class:"btn btn-outline-danger"%>
         <% end %>
       </div>
     </div> <br>
   </div> 
   <% end %>
   <% end %>   
</div>
<br>
<%= link_to "Back to users", root_path , class:"btn btn-success"%>

app/views/events/new.html.erb
<span> If you don't know room capacity then click here </span><%= link_to "Room Capacity", rooms_path%><center>
<h1 style=" color: white;">Create New Schedule</h1>

<%= render "form", event: @event %><br>

<div>
<%= link_to "Back to users", root_path , class:"btn btn-success"%>
</div>
</center>

app/views/events/show.html.erb
<h1 style=" color: white;">Schedule Meetings Details:-</h1>
<div>
  <p style=" color: white;"><b> Purpose: </b><%= @event.purpose %></p>
  <p style=" color: white;"><b> People: </b><%= @event.people %></p>
  <p style=" color: white;"><b> Start Time: </b><%= @event.start_date %></p>
  <p style=" color: white;"><b> End Time: </b><%= @event.end_date %></p>
  <p style=" color: white;"><b> Room: </b><%= @event.room.room %></p>
  <p style=" color: white;"><b> Host: </b><%= @event.user.to_s %></p>
</div>
<div>
 <%= link_to "Edit this Meeting", edit_event_path(@event) %> |
 <%= link_to "Back to events", root_path %>
</div>