config/routes.rb
  Rails.application.routes.draw do  

       root "sessions#welcome"
     
       get 'login', to: 'sessions#new'   
       post 'login', to: 'sessions#create'  
       get 'welcome', to: 'sessions#welcome'   
       get 'authorized', to: 'sessions#page_requires_login'
       get '/logout' => 'sessions#destroy'
       get '/search', to: 'events#search'
       
       resources :users
       resources :events
       resources :rooms
       resources :password_resets

       get '/expried_index', to: 'events#expried_index'

  end

app/models/room.rb
class Room < ApplicationRecord
	has_many :events, dependent: :destroy
	
	validates  :room_name, presence: true

    validates :capacity, :numericality => { :greater_than_or_equal_to => 1}

    def room
    	"#{room_name}"
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  
 before_action :set_room, only: %i[ show edit update destroy ]

  def index
    @rooms = Room.all
  end

  def show
  end

  def new
    @room = Room.new
  end

  def edit
  end

  def create
    @room = Room.create(room_params)
        if @room.save
          flash[:notice] = "Room created successfully."
          redirect_to @room
        else
          render :new, status: :unprocessable_entity
        end
  end

  def update
      if @room.update(room_params)
         flash[:notice] = "Room updated successfully."
         redirect_to @room
      else
         render :edit, status: :unprocessable_entity
      end
  end

  def destroy
     @room.destroy
     flash[:notice] = "Room Destroy successfully."  
     redirect_to root_path, status: :see_other
  end

  private
    def set_room
      @room = Room.find(params[:id])
    end

    def room_params
      params.require(:room).permit(:room_name, :capacity)
    end

end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= form_for @room do |f|%>

  <% if @room.errors.any? %>
    <div style="color: red">
      <ul>
        <% @room.errors.each do |error| %>
          <li style=" color: white;"><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div style=" color: white;">
<%= f.label :room_name , style: "display: block"%>
<%= f.text_field :room_name %>
</div>
<div style=" color: white;">
<%= f.label :capacity , style: "display: block"%>  
<%= f.text_field :capacity%>
</div><br>
<%= f.submit  "Save" , class:"btn btn-primary"%><%end%>

app/views/rooms/edit.html.erb
<center><h1 style=" color: white;">Edit Details:-</h1>
<%= render "form", event: @event %><br>
<%= link_to "Back", rooms_path , class:"btn btn-success"%>
</center>

app/views/rooms/index.html.erb
<center><h1 style=" color: white;">All Rooms:-</h1></center>
<div class="row">
  <% @rooms.each do |room| %>
   <div class="col-sm-6" >
     <div class="card navbar-light bg-light"  style="background-image: url(https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQUHfjWn2Sa5jFNRnlbskEQdXyN1tRhH1dpdQ&usqp=CAU); background-repeat: no-repeat; background-size: cover;">
       <div class="card-body" >
        <b>Room Name:-</b> <%= room.room_name %></p>
        <b>Room Capacity:-</b> <%= room.capacity %></p>
         <% if current_user.role == "HR" %>
         <%= link_to "Edit Room", edit_room_path(room) %> |
         <%= button_to "Delete User", room, method: :delete , class:"btn btn-outline-danger"%>
         <% end %>
       </div>
     </div> <br>
   </div> 
   <% end %>  
</div>
<br>
<% if current_user.role == "HR" %>
<%= link_to "Add Room", new_room_path , class:"btn btn-success"%> | <% end %>
<%= link_to "Back to users", root_path , class:"btn btn-success"%>

app/views/rooms/new.html.erb
<br><br><center>
<h1 style=" color: white;">Add Room</h1>
<%= render "form", event: @event %><br>
<%= link_to "Back", rooms_path , class:"btn btn-success"%>
</center>

app/views/rooms/show.html.erb
<center><p><b> Room: </b><%= @room.room_name %></p>
 <p><b> Room Capacity: </b><%= @room.capacity %></p>
 <%= link_to "Back", rooms_path , class:"btn btn-success"%>
</center>