config/routes.rb
  Rails.application.routes.draw do  

       root "sessions#welcome"
     
       get 'login', to: 'sessions#new'   
       post 'login', to: 'sessions#create'  
       get 'welcome', to: 'sessions#welcome'   
       get 'authorized', to: 'sessions#page_requires_login'
       get '/logout' => 'sessions#destroy'
       get '/search', to: 'events#search'
       
       resources :users
       resources :events
       resources :rooms
       resources :password_resets

       get '/expried_index', to: 'events#expried_index'

  end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Meeting</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body style="background-image: url(https://cdn2.hubspot.net/hubfs/202339/canvas/images/parallax/Website-Design-Background.png); background-repeat: no-repeat; background-size: cover;">
    <nav class="navbar navbar-light bg-light bg-success p-2 text-dark bg-opacity-25 ">
    <div class="container-fluid">

     <% if logged_in? %> 

    <div class="dropdown">
    <button class="btn btn-light dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
    Profile
    </button> 
    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
     <% if current_user.role == "HR" %>
     <%= link_to "All Rooms", rooms_path , class:"dropdown-item"%>
     <%= link_to "All Users", users_path , class:"dropdown-item"%>
     <%= link_to "All Expried Meeting", expried_index_path , class:"dropdown-item"%>
     <%= link_to "Add Employee", new_user_path , class:"dropdown-item"%>

     <% end %>
     <%= button_to "All Meetings", '/events', method: :get, class:"dropdown-item"%>
     <%= button_to "Your Details ", user_path(current_user), method: :get, class:"dropdown-item"%>
     <%= button_to "New Event", '/events/new', method: :get, class:"dropdown-item"%>
     <%= button_to "Logout", '/logout', method: :get, class:"dropdown-item"%>
    </ul>
    </div> 

     <%= image_tag("logo.png" , :size => "170x30") %>

    <form class="form-inline" action="/search" method="GET">
      <div class="container" class="justify-content-center">
        <div class="row height d-flex justify-content-center align-items-center">
          <table>
            <td><input type="/search" class="form-control" placeholder="purpose" aria-label="Search" name="query" method = "GET" class="form-control form-control-lg"> </td>
            <td><button class="btn btn-primary col-md-12" type="submit" >Search</button> </td>
          </table>
        </div>
      </div>
    </form>

      <% else %>
      <%= button_to "Login", '/login', method: :get, class:"btn btn-success"%>
      <% end %> 
    </div>
    </nav>

      <% if logged_in? %> 
      <p style="text-align: right; padding-right: 20px; color: white;">Welcome : <span style="color: red;"><b><%= current_user.username %></b></span></p>
      <% end %>

      <% if flash[:notice] %>
      <div class="alert alert-primary"><%= flash[:notice] %></div>
      <% end %>   

      <%= yield %>

  </body>
  
</html>